"""Builders for prompts and generated context documents."""

from __future__ import annotations

import datetime as dt

from contextdrop.config import project_name
from contextdrop.core.summarizer import task_lines
from contextdrop.services.parser import extract_saved_timestamp, extract_section


def build_system_prompt(name: str) -> str:
    return f"""# ContextDrop System Prompt - paste this at the start of every agent session

---

You are working on the project: **{name}**

The project brain is stored in `.ctx/`. Before doing anything:
1. Read `.ctx/brain.md` for stack, decisions, and conventions
2. Read `.ctx/handoff.md` for what was last done and what's next
3. Read `.ctx/tasks.json` for the full task board

After **every meaningful response** (writing code, making a decision, completing a task), append this block at the very end of your reply:

---CTX-UPDATE---
done: [what you just completed, or 'none']
decision: [any architecture/tech choice made, or 'none']
next: [what should happen next]
bug: [any issue discovered, or 'none']
---END-CTX-UPDATE---

This is critical. It lets the project brain stay updated automatically even if this session ends unexpectedly.

---
"""


def build_load_prompt(brain: str, handoff: str, tasks: dict) -> str:
    name = project_name()
    stack = extract_section(brain, "Stack") or "see brain.md"
    arch = extract_section(brain, "Architecture decisions") or "(none yet)"
    env = extract_section(brain, "Environment") or "(none)"
    conv = extract_section(brain, "Naming conventions") or "(none)"

    todo_list = "\n".join(f"  - {t['task']}" for t in tasks.get("todo", [])) or "  (none)"
    done_list = "\n".join(f"  - {t['task']}" for t in tasks.get("done", [])[-5:]) or "  (none yet)"
    in_prog = "\n".join(f"  - {t['task']}" for t in tasks.get("in_progress", [])) or "  (none)"

    last_done = extract_section(handoff, "What was done this session") or "(first session)"
    last_next = extract_section(handoff, "Next task for new agent") or "(see todo list)"
    last_bugs = extract_section(handoff, "Known blockers") or "(none)"
    saved = extract_saved_timestamp(handoff)
    last_saved = f" (saved {saved})" if saved else ""

    # Text shape is intentionally preserved from the prototype so existing user
    # handoff habits and downstream parsers keep working.
    return f"""===========================================
  CONTEXTDROP - PROJECT BRAIN for {name}
===========================================

You are resuming work on an existing project. Read all of this before writing any code.

## Project: {name}

## Stack
{stack}

## Architecture decisions
{arch}

## Environment & config
{env}

## Naming conventions
{conv}

## Last session summary{last_saved}
What was built: {last_done}
Known bugs/blockers: {last_bugs}

## Task board
In progress:
{in_prog}

TODO (do these next, in order):
{todo_list}

Recently done (do NOT redo these):
{done_list}

## Your first task
{last_next}

===========================================
IMPORTANT: After each meaningful response, append this block:

---CTX-UPDATE---
done: [what you just completed]
decision: [any arch/tech choice made, or 'none']
next: [what comes after this]
bug: [any issue found, or 'none']
---END-CTX-UPDATE---

This keeps the project brain updated automatically.
===========================================
"""


def build_report_markdown(brain: str, handoff: str, tasks: dict) -> str:
    name = project_name()
    stack = extract_section(brain, "Stack") or "Not specified"
    arch = extract_section(brain, "Architecture decisions") or "None recorded"
    env_conf = extract_section(brain, "Environment") or "None"
    conv = extract_section(brain, "Naming conventions") or "None"
    key_files = extract_section(brain, "Key files") or "(empty)"

    last_done = extract_section(handoff, "What was done this session") or "No sessions saved yet"
    last_next = extract_section(handoff, "Next task for new agent") or "Not set"
    last_bugs = extract_section(handoff, "Known blockers") or "None"
    last_saved = extract_saved_timestamp(handoff) or "Never"

    done_list = tasks.get("done", [])
    todo_list = tasks.get("todo", [])
    prog_list = tasks.get("in_progress", [])
    blocked_list = tasks.get("blocked", [])

    total = len(done_list) + len(todo_list) + len(prog_list) + len(blocked_list)
    progress_pct = round(len(done_list) / total * 100) if total > 0 else 0
    bar_filled = round(progress_pct / 5)
    bar = "#" * bar_filled + "." * (20 - bar_filled)
    now_str = dt.datetime.now().strftime("%Y-%m-%d %H:%M")

    return f"""# {name} - context snapshot
> Generated by ContextDrop | {now_str} | Last session saved: {last_saved}

---

## READ THIS FIRST

You are resuming work on **{name}**. This file is your complete project brain.
Read every section before writing a single line of code.

---

## Stack

{stack}

---

## Architecture decisions
> These are final. Do not re-decide or second-guess these.

{arch}

---

## Naming conventions

{conv}

---

## Environment & config

{env_conf}

---

## File tree

```
{key_files}
```

---

## Last session summary
_Saved: {last_saved}_

**What was built:**
{last_done}

**Known bugs / blockers:**
{last_bugs}

---

## Task board
Progress: `{bar}` {progress_pct}% ({len(done_list)}/{total} done)

### In progress
{task_lines(prog_list, "- [~]")}

### Todo - do these in order
{task_lines(todo_list, "- [ ]")}

### Done - do NOT redo these
{task_lines(done_list, "- [x]")}

### Blocked
{task_lines(blocked_list, "- [!]")}

---

## Your first task

{last_next}

---

## Auto-update instruction

After **every meaningful response**, paste this block at the end of your reply.
The project brain will be updated automatically.

```
---CTX-UPDATE---
done: [what you just completed, or 'none']
decision: [any architecture/tech choice made, or 'none']
next: [what should happen next]
bug: [any issue found, or 'none']
---END-CTX-UPDATE---
```

---
_ContextDrop | ctx report | https://github.com/your-repo/contextdrop_
"""
