"""Builders for prompts and generated context documents."""

from __future__ import annotations

import datetime as dt

from contextdrop.config import project_name
from contextdrop.core.summarizer import task_lines
from contextdrop.services.parser import extract_saved_timestamp, extract_section


def build_system_prompt(name: str) -> str:
    return f"""# ContextDrop System Prompt - paste this at the start of every agent session

---

You are working on the project: **{name}**

The project brain is stored in `.ctx/`. Before doing anything:
1. Read `.ctx/brain.md` for stack, decisions, and conventions
2. Read `.ctx/handoff.md` for what was last done and what's next
3. Read `.ctx/tasks.json` for the full task board

After **every meaningful response** (writing code, making a decision, completing a task), append this block at the very end of your reply:

---CTX-UPDATE---
done: [what you just completed, or 'none']
decision: [any architecture/tech choice made, or 'none']
next: [what should happen next]
bug: [any issue discovered, or 'none']
---END-CTX-UPDATE---

This is critical. It lets the project brain stay updated automatically even if this session ends unexpectedly.

---
"""


def build_load_prompt(brain: str, handoff: str, tasks: dict) -> str:
    name = project_name()
    stack = _clean_section(extract_section(brain, "Stack") or "see brain.md")
    arch = _clean_section(extract_section(brain, "Architecture decisions") or "")
    env = _clean_section(extract_section(brain, "Environment") or "")
    conv = _clean_section(extract_section(brain, "Naming conventions") or "")

    todo_list = _task_names(tasks.get("todo", []), limit=5) or "none"
    done_list = _task_names(tasks.get("done", [])[-5:], limit=5) or "none"
    in_prog = _task_names(tasks.get("in_progress", []), limit=3) or "none"

    last_done = _clean_section(extract_section(handoff, "What was done this session") or "first session", limit=900)
    last_next = _clean_section(extract_section(handoff, "Next task for new agent") or "see todo list", limit=220)
    last_bugs = _clean_section(extract_section(handoff, "Known blockers") or "none", limit=220)
    saved = extract_saved_timestamp(handoff)
    meta = f"{name}{f' | saved {saved}' if saved else ''}"

    lines = [
        f"CONTEXTDROP: {meta}",
        f"Stack: {stack}",
    ]
    if arch:
        lines.append(f"Decisions: {arch}")
    if env:
        lines.append(f"Env: {env}")
    if conv:
        lines.append(f"Conventions: {conv}")
    lines.extend(
        [
            f"Last: {last_done}",
            f"Bugs: {last_bugs}",
            f"Doing: {in_prog}",
            f"Todo: {todo_list}",
            f"Done: {done_list}",
            f"First: {last_next}",
            "Reply update block: ---CTX-UPDATE--- done: ... | decision: ... | next: ... | bug: ... ---END-CTX-UPDATE---",
        ]
    )
    return "\n".join(lines) + "\n"


def _task_names(items: list, limit: int) -> str:
    names = []
    for item in items[:limit]:
        task = item.get("task", item) if isinstance(item, dict) else item
        names.append(str(task))
    return "; ".join(names)


def _clean_section(value: str, limit: int = 500) -> str:
    lines = []
    for raw in value.splitlines():
        line = raw.strip()
        if not line or line.startswith("<!--") or line in {"-", "- ", "(none)", "(none yet)"}:
            continue
        lines.append(line)
    compact = " ".join(lines).strip()
    if len(compact) > limit:
        return compact[: limit - 3].rstrip() + "..."
    return compact


def build_report_markdown(brain: str, handoff: str, tasks: dict) -> str:
    name = project_name()
    stack = extract_section(brain, "Stack") or "Not specified"
    arch = extract_section(brain, "Architecture decisions") or "None recorded"
    env_conf = extract_section(brain, "Environment") or "None"
    conv = extract_section(brain, "Naming conventions") or "None"
    key_files = extract_section(brain, "Key files") or "(empty)"

    last_done = extract_section(handoff, "What was done this session") or "No sessions saved yet"
    last_next = extract_section(handoff, "Next task for new agent") or "Not set"
    last_bugs = extract_section(handoff, "Known blockers") or "None"
    last_saved = extract_saved_timestamp(handoff) or "Never"

    done_list = tasks.get("done", [])
    todo_list = tasks.get("todo", [])
    prog_list = tasks.get("in_progress", [])
    blocked_list = tasks.get("blocked", [])

    total = len(done_list) + len(todo_list) + len(prog_list) + len(blocked_list)
    progress_pct = round(len(done_list) / total * 100) if total > 0 else 0
    bar_filled = round(progress_pct / 5)
    bar = "#" * bar_filled + "." * (20 - bar_filled)
    now_str = dt.datetime.now().strftime("%Y-%m-%d %H:%M")

    return f"""# {name} - context snapshot
> Generated by ContextDrop | {now_str} | Last session saved: {last_saved}

---

## READ THIS FIRST

You are resuming work on **{name}**. This file is your complete project brain.
Read every section before writing a single line of code.

---

## Stack

{stack}

---

## Architecture decisions
> These are final. Do not re-decide or second-guess these.

{arch}

---

## Naming conventions

{conv}

---

## Environment & config

{env_conf}

---

## File tree

```
{key_files}
```

---

## Last session summary
_Saved: {last_saved}_

**What was built:**
{last_done}

**Known bugs / blockers:**
{last_bugs}

---

## Task board
Progress: `{bar}` {progress_pct}% ({len(done_list)}/{total} done)

### In progress
{task_lines(prog_list, "- [~]")}

### Todo - do these in order
{task_lines(todo_list, "- [ ]")}

### Done - do NOT redo these
{task_lines(done_list, "- [x]")}

### Blocked
{task_lines(blocked_list, "- [!]")}

---

## Your first task

{last_next}

---

## Auto-update instruction

After **every meaningful response**, paste this block at the end of your reply.
The project brain will be updated automatically.

```
---CTX-UPDATE---
done: [what you just completed, or 'none']
decision: [any architecture/tech choice made, or 'none']
next: [what should happen next]
bug: [any issue found, or 'none']
---END-CTX-UPDATE---
```

---
_ContextDrop | ctx report | https://github.com/your-repo/contextdrop_
"""
